### ISSUE TITLE
userService should be able to return information about another user

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps-js#5]
The user should have set the `public` flag.
The user will be specified by username, e.g. like this:
`userService.loadUser('slaweet')`

**Comment by thran** [comment]
use userStatService.getStats(false, 'slaweet') or userStatService.getStatsPost(false, 'slaweet')

**Comment by slaweet** [comment]
Does `userStatService.getStats` return also info about the user such as first_name and last_name?

**Comment by thran** [comment]
Oh, I misunderstood issue. Please specify _information about another user_. We can attach name to userStats but I am not sure what is exact use of this feature...

**Comment by slaweet** [comment]
The use is "public profile", such as http://slepemapy.cz/u/slaweet
the info there is:
Points 2821
First name Vít
Surname Stanislav
