### ISSUE TITLE
JS error logging: log also stacktrace

### ISSUE THREAD

**Issue by slaweet** [adaptive-learning/proso-apps-js#8]

**Comment by papousek** [comment]
It is technically hard, because I am not sure how to convert stack trace to JSON, and then dump it to string.

**Comment by slaweet** [comment]
I don't need JSON, just something like this:
http://stackoverflow.com/questions/6715571/how-to-get-result-of-console-trace-as-string-in-javascript-with-chrome-or-fire/28118170#28118170
Without a stack trace the logs are really difficult to use.

**Comment by slaweet** [comment]
Or at least file and line number.

**Comment by papousek** [comment]
resolved by 7805feef966c62c8223df56c1426c2e6fb13aca6
